### PR TITLE
Generic Filter

### PR DESCRIPTION
**Pull request by timominous**
A generic filter instead of 2 different filter types.

### CODE REVIEW

**Comment by tannernelson** [comment]
Needing to use 'value' with equality filters and 'valueSet' with subset filters could be confusing. 

Is there anyway to making 'value' return an array or a string depending on whether it's a subset or equality filter?

**Comment by tannernelson** [comment]
I do like being able to view all filter types in one switch though. This allows the compiler to notify you of unhandled filters.

**Comment by timominous** [comment]
@tannernelson are you talking about what `eitherValue` (poorly named) does?

**Comment by tannernelson** [comment]
No, that returns any. It should be able to generically return either an array or a string so it won't require casting.

**Comment by timominous** [comment]
@tannernelson I'm not sure if that can be done. Let me look it up.

**Comment by Prince2k3** [comment]
I would like to see the comparison string as part of the enum in some way so there would be no need for the switch statement

**Comment by timominous** [comment]
@Prince2k3 but the operators should come from the different drivers.

**Comment by tannernelson** [comment]
```swift
protocol Filter<T> {
   var key: String
   var value: T
}
```

Could something like this work?

**Comment by Prince2k3** [comment]
@timominous I see what you mean But with what @tannernelson just posted I have to agree with that approach. Even reducing the Comparison to just one enum.

**Comment by timominous** [comment]
@tannernelson @Prince2k3 should the comparison enum be merged into one?

**Comment by timominous** [comment]
@tannernelson @Prince2k3 Would you take a look at the newly introduced changes? Thanks.

**Comment by Prince2k3** [comment]
I think that you use the generic approach that @tannernelson specified. Doing with a protocol and extension is doing it the long way. 

```
protocol Filter<T> {
   var key: String
   var value: T
}
class EqualityFilter: Filter<String> {
   var key: String
   var value: String
  init(key: String, comparison: EqualityComparison, value: String)
}
class SubsetFilter: Filter<[String]> {
   var key: String
   var value: [String]
 init(key: String, comparison: SubsetComparison, value: [String])
}
```
something like this so that you don't need the extension that you have

**Comment by timominous** [comment]
@Prince2k3 The `Filter` protocol will then be available for use a generic constraint. This is in conflict with what we have in `Query`. There will be no way to declare an array (afaik) with objects conforming to `Filter`. 

https://github.com/qutheory/fluent/blob/master/Sources/Query.swift#L3

**Comment by Prince2k3** [comment]
```
protocol Filter {
    associatedtype FilterValue
    var key: String { get set }
    var value: FilterValue { get set }
}

class EqualityFilter: Filter {
    var key: String
    var value: String
}

class SubsetFilter: Filter {
    var key: String
    var value: [String]
}
```
For the Query class add this
```
class Query<F: Filter> {
    var filters = [F]()
}

```
If you do it this way it should allow for the filter array in Query class to work just fine

**Comment by timominous** [comment]
I see. I'll try it out once I have some free time.

**Comment by timominous** [comment]
@Prince2k3 as we've discussed, we can't do that since we would have to declare query initialization like
```
let query = Query<SomethingThatConformsToModel, EqualityFilter>()
```
which forbids us to use `SubsetFilters`.

Any opinion on this @tannernelson?

**Comment by timominous** [comment]
I think I'ill just close this now in favor of tokenized statements.

**Pull request closed without merging**
